pipeline {
    agent any

    stages {

        stage('Clone Repository') {
            steps {
                git credentialsId: 'github-creds',
                    url: 'https://github.com/kivuvans/alx-backend-python.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh '''
                python3 -m venv venv
                . venv/bin/activate
                pip install --upgrade pip
                pip install -r requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                . venv/bin/activate
                pytest --junitxml=test-report.xml
                '''
            }
        }
    }

    post {
        always {
            junit 'test-report.xml'
        }
    }
}
