#!/bin/bash

echo "Deploying BLUE version..."
kubectl apply -f blue_deployment.yaml

echo "Deploying GREEN version..."
kubectl apply -f green_deployment.yaml

echo "Applying Service..."
kubectl apply -f kubeservice.yaml

echo "Checking GREEN logs..."
kubectl logs -l version=green
